name: Continuous Integration
on: 
  push: 
    branches:
      - main
  workflow_dispatch: #This line allows you to run the workflow manually from the GitHub Actions page
  workflow_call: #This line allows you to run the workflow from another workflow

permissions:
  contents: read
  id-token: write

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::463470967986:role/Deployer"
          role-session-name: Deploy

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build Stack
        run: sam build

      - name: Deploy Stack
        run: sam deploy